In [2]:
import numpy as np

In [3]:
a = np.array([0,-7/8],)
b = np.array([[1,1,1,1,1,1,1,1],[1,2,3,4,5,6,7,8]])
c = a.T @ b
np.shape(a)

(2,)

ASS 2

Q1


In [4]:
x = np.array([[1,-2],[1,3]])
w = np.array([1.5672,0.0821])
t = np.array([0,2])
np.shape(w)
l = x@w - t
c = 1/3 * (l.T @ l)
c

0.6677304166666667

Q2


In [16]:
q = np.array([[1/3,0,0],[0,-3.3391,3.5117],[0,3.5117,-3.3362]])
x = np.array([[1,1.336,1.225],[1,-0.267,0],[1,-1.069,-1.225]])
t = np.array([3,1,2])
B = np.array([[0,0,0],[0,0.3,0],[0,0,0.3]])
np.linalg.inv(x.T @ x + B).T @ x.T @t

array([ 2.        ,  0.76115151, -0.30820068])

In [6]:
def sigmoid(z):
    """
    Compute the sigmoid of z

    Args:
        z (ndarray): A scalar, numpy array of any size.

    Returns:
        g (ndarray): sigmoid(z), with the same shape as z
         
    """

    g = 1/(1+np.exp(-z))
   
    return g

In [7]:
y_t = np.array([sigmoid(0),sigmoid(8)-1,sigmoid(5),sigmoid(0)-1])

x_T = np.array([[1,-1,-2],[1,2,6],[1,3,3],[1,2,-2]])
1/4 * (x_T.T@y_t)

array([0.24824295, 0.36981269, 0.74447734])

In [9]:
from numpy import array
a = 1 
b = a
a = 2
print(a,b)

2 1


In [70]:
# some convenient code
def l_ce(t, y_pred):
    y_pred[y_pred == 1] = 0.99999999999999999
    y_pred[y_pred == 0] = 0.00000000000000001
    return np.dot(-1 * t, np.log(y_pred)) - np.dot((1 - t), np.log(1 - y_pred))

def sigmoid(z):
    return (1/ (1 + np.exp(-z)))

def relu(h):
    h[h < 0] = 0
    return h


def d_relu(g):
    # relu derivative
    g[g >= 0] = 1
    g[g < 0] = 0
    return g


def new_w(w, w_J):
    alpha = 2
    w_new = w - np.dot(alpha, w_J)
    return w_new

def neural_net_GD(x, t, Ws):
    L = len(Ws)

    zs = []
    hs = []

    # fwd
    z1 = np.dot(Ws[0], np.r_[1, x.T][:, None])
    # print("z1: {0}\n".format(z1))
    h1 = relu(z1.copy())
    # print("h1: {0}\n".format(h1))
    zs.append(z1)
    hs.append(h1)
    # z2 = np.dot(W2, np.c_[1, h1.T].T)
    # # print("z2: {0}\n".format(z2))
    # h2 = relu(z2.copy())
    # # print("h2: {0}\n".format(h2))

    # middle layers
    h_prev = h1
    for l in range(1,L-1):
        z = np.dot(Ws[l], np.c_[1, h1.T].T)
        h = relu(z.copy())
        zs.append(z)
        hs.append(h)
        h_prev = h

    zd = np.dot(Ws[-1], np.c_[1, h_prev.T].T)
    zs.append(zd)
    print('zs = ',zs)
    # print("z3: {0}\n".format(z3))
    y = 1 / (1 + np.exp(-zd))
    hs.append(y) # y is h_d
    print('hs = ',hs)
    # print("y: {0}\n".format(y))

    # bwd
    # z is 1 shorter than w cus (d-1) d = 3
    w_Js = []
    z_Js = []
    dj_dz_d = -t + y  # gradient of cross-entropy loss dJ/dz
    
    wd_J = dj_dz_d * np.c_[1, h_prev.T]
    w_Js.append(wd_J)
    zdm1_J = np.multiply(d_relu(zs[-2]), Ws[-1][:, 1:].T * dj_dz_d)  # element wise multiplication
    z_Js.append(zdm1_J)

    # middle layers (if more than one)
    for l in reversed(range(1, L-1)):
        # dz of current layer
        dz_current = np.multiply(d_relu(zs[l-1]), np.dot(Ws[l][:, 1:].T, z_Js[0]))
        z_Js.insert(0, dz_current)  # prepend so z_Js order matches layers
        
        # gradient for weights at this layer
        h_input = hs[l-1] if l > 1 else h1
        w_grad = np.dot(dz_current, np.c_[1, h_input.T])
        w_Js.insert(0, w_grad)  # prepend so w_Js order matches Ws

    
    w1_J = np.dot(z_Js[0], np.r_[1, x.T][None, :])
    w_Js.insert(0, w1_J)
    
    print('w_Js = ', w_Js)
    print('z_Js = ',z_Js)
    # new weights
    # W1_new = new_w(Ws[0], w_Js[0])
    # W2_new = new_w(Ws[1], w_Js[1])
    # W3_new = new_w(Ws[2], w_Js[2])
    w_new = []
    for i in range(len(Ws)):
        w_new.append(new_w(Ws[i], w_Js[i]))

    return y.item(0), w_new

In [69]:
import numpy as np

np.random.seed(0)

# # input (2 features)
# x = np.array([0.5, -0.2])

# # target
# t = 1

# network architecture
# input=2 → hidden1=3 → hidden2=2 → output=1

# W1 = np.random.randn(3, 3)   # (3 neurons, 1 bias + 2 inputs)
# W2 = np.random.randn(2, 4)   # (2 neurons, 1 bias + 3 hidden)
# W3 = np.random.randn(1, 3)   # (1 neuron, 1 bias + 2 hidden)

W1 = np.array([
    [0.5, -1, -0.5, 1.5],
    [1, 0.2, -0.4, -1]
])

W2 = np.array([
    [-1.5, 1, 0.4],
    [-1, -2, 0.5]
])

# Output layer needs to be 2D for consistent matrix operations
W3 = np.array([[-2, 1, -1]])  # shape (1,3)

# Input and target
x = np.array([1, -1, 2])
t = 1

print("Before update:")
print("W1\n", W1)
print("W2\n", W2)
print("W3\n", W3)

y, ws = neural_net_GD(x, t, [W1, W2, W3])

print("\nPrediction:", y)

print("\nAfter one GD step:")
print("W1\n", ws[0])
print("W2\n", ws[1])
print("W3\n", ws[2])

Before update:
W1
 [[ 0.5 -1.  -0.5  1.5]
 [ 1.   0.2 -0.4 -1. ]]
W2
 [[-1.5  1.   0.4]
 [-1.  -2.   0.5]]
W3
 [[-2  1 -1]]
zs =  [array([[ 3. ],
       [-0.4]]), array([[ 1.5],
       [-7. ]]), array([[-0.5]])]
hs =  [array([[3.],
       [0.]]), array([[1.5],
       [0. ]]), array([[0.37754067]])]
w_Js =  [array([[-0.62245933, -0.62245933,  0.62245933, -1.24491866],
       [ 0.        ,  0.        ,  0.        ,  0.        ]]), array([[-0.62245933, -1.86737799,  0.        ],
       [ 0.        ,  0.        ,  0.        ]]), array([[-0.62245933, -0.933689  , -0.        ]])]
z_Js =  [array([[-0.62245933],
       [-0.        ]]), array([[-0.62245933],
       [ 0.        ]])]

Prediction: [[0.37754067]]

After one GD step:
W1
 [[ 1.74491866  0.24491866 -1.74491866  3.98983732]
 [ 1.          0.2        -0.4        -1.        ]]
W2
 [[-0.25508134  4.73475599  0.4       ]
 [-1.         -2.          0.5       ]]
W3
 [[-0.75508134  2.86737799 -1.        ]]


Before update:
W1
 [[ 0.5 -1.  -0.5  1.5]
 [ 1.   0.2 -0.4 -1. ]]
W2
 [[-1.5  1.   0.4]
 [-1.  -2.   0.5]]
W3
 [[-2  1 -1]]

Prediction: 0.3775406687981454

After one GD step:
W1
 [[ 1.74491866  0.24491866 -1.74491866  3.98983732]
 [ 1.          0.2        -0.4        -1.        ]]
W2
 [[-0.25508134  4.73475599  0.4       ]
 [-1.         -2.          0.5       ]]
W3
 [[-0.75508134  2.86737799 -1.        ]]